parameters:
    # ...
    mailer.transport: sendmail

services:
    teste:
        class:     "Vox\\Treinamento\\DependencyInjection\\Teste"
    teste_manager:
        class:     "Vox\\Treinamento\\DependencyInjection\\TesteManager"
        arguments: ["@teste"]
    cafe:
        class:  "Vox\\Treinamento\\Exercicio1\\Cafe"
    pedido:
        class: "Vox\\Treinamento\\Exercicio1\\Pedido"
    chantily:
        class: "Vox\\Treinamento\\Exercicio1\\Adicionais\\Chantily"
    duplo:
        class: "Vox\\Treinamento\\Exercicio1\\Adicionais\\Duplo"
    expresso:
        class: "Vox\\Treinamento\\Exercicio1\\Adicionais\\Expresso"
    factory_cupom_fiscal:
        class: "Vox\\Treinamento\\Exercicio1\\CupomFiscalFactory"